<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use Doctrine\ORM\Query\AST\LikeExpression;
use function MongoDB\BSON\fromJSON;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @param null $filter
     * @return \Doctrine\ORM\Query
     */
    public function listAll($filter = null)
    {
        $articlesQuery = $this->createQueryBuilder('a');

        if ($filter) {
            $articlesQuery->where('a.title LIKE :title')
                ->setParameter('title', '%' . $filter . '%');
        }

        return $articlesQuery->getQuery();
    }


    /**
     * @param $id
     */
    public function showOne($id)
    {
        $oneArticle = $this->find($id);

        return $oneArticle;
    }


    /**
     * @param $id
     */
    public function delete($id = null)
    {
        if ($id == null) {

            $this->createQueryBuilder('a')
                ->delete('AppBundle\Entity\Article')
                ->getQuery()
                ->execute();
        } else {

            $deletingRecord = $this->find($id);
            $em = $this->getEntityManager();
            $em->remove($deletingRecord);
            $em->flush();
        }
    }

    /**
     * @param Article $article
     */
    public function update(Article $article)
    {
        $em = $this->getEntityManager();
        $em->persist($article);
        $em->flush();
    }

}
