<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{


    public function listAll()
    {
        $allArticles = $this->createQueryBuilder('a');

        return $allArticles;
    }


    /**
     * @param $id
     */
    public function showOne($id)
    {
        $oneArticle = $this->find($id);

        return $oneArticle;
    }


    /**
     * @param $id
     */
    public function delete($id = null)
    {
        if ($id == null)
        {

            $this->createQueryBuilder('a')
                ->delete('AppBundle\Entity\Article')
                ->getQuery()
                ->execute();
        } else {

            $deletingRecord = $this->find($id);
            $em = $this->getEntityManager();
            $em->remove($deletingRecord);
            $em->flush();
        }

    }

    /**
     * @param Article $article
     */
    public function update(Article $article)
    {
        $em = $this->getEntityManager();
        $em->persist($article);
        $em->flush();

    }

    public function myQuery()
    {
        $qb = $this->createQueryBuilder('a');

        $zm1 = $qb->select('a.title')
            ->where('a.id> :id')
            ->setParameter('id', '12ma')
            ->orderBy('a.title', 'ASC')
            ->getQuery();

        $queriedArticle = $zm1->getResult();

        return $queriedArticle;

    }


}
