<?php

namespace AppBundle\Repository;
use Doctrine\Bundle\DoctrineBundle\DoctrineBundle;
use Doctrine\ORM\Mapping;
use JMS\SerializerBundle\JMSSerializerBundle;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    private $JMS;
    private $doctrine;

//        $this->JMS = $JMSSerializerBundle;

    public function __construct( $doctrine)
    {

        $this->doctrine = $doctrine;
    }

    public function showArticles()
    {
        dump($this->doctrine);
        die;
        $zm1 = $this->doctrine->getRepository('AppBundle:Article')->findAll();



        return $zm1;
   }



}
