<?php

namespace AppBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $id
     */
    public function listComments ($id) {

        $queryBuilder = $this->createQueryBuilder('c')
            ->where('c.idArticle =  :idArticle')
            ->setParameter('idArticle', $id);

        return $queryBuilder->getQuery()->getResult();
    }

    /**
     * @param $comment
     */
    public function createComment($comment) {

        $em = $this->getEntityManager();
        $em->persist($comment);
        $em->flush();
    }
}
