<?php

namespace AppBundle\Repository;

/**
 * MyUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyUserRepository extends \Doctrine\ORM\EntityRepository
{

}
