# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.repo.articles:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Article

    app.repo.comments:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Commentary

    app.notifier.mail:
      class: AppBundle\Service\Notifier
      arguments:
            - "@mailer"
            - "@logger"

    app.datatable.article:
      class: AppBundle\Datatables\ArticleDatatable
      parent: sg_datatables.datatable.abstract

    app.factory.images:
      class: AppBundle\Factory\Image\ImageFactory