api_list_articles:
    path: /api/art
    methods: GET
    defaults: { _controller: AppBundle:Article:list }

api_show_article:
    path: /api/art/{id}
    methods: GET
    defaults: { _controller: AppBundle:Article:show }
    requirements:
        id: '\d+'

api_delete_article:
    path: /api/art/{id}
    methods: DELETE
    defaults: { _controller: AppBundle:Article:delete }
    requirements:
         id: '\d+'

api_update_article:
    path: /api/art/{id}
    methods: PUT
    defaults: { _controller: AppBundle:Article:update }
    requirements:
         id: '\d+'

api_create_article:
    path: /api/art
    methods: POST
    defaults: { _controller: AppBundle:Article:create }


article_admin:
    path: /user
    methods: GET
    defaults: { _controller: AppBundle:Web:admin }

article_index:
    path: /articles
    methods: GET
    defaults:  { _controller: AppBundle:Web:index }

list_all_articles:
    path: /a
    methods: GET
    defaults: { _controller: AppBundle:Web:listAll }

show_article:
    path: /articles/read/{id}
    methods: ['GET' , 'POST']
    defaults: { _controller:  AppBundle:Web:show }
    requirements:
        id: '\d+'

create_article:
    path: /create
    methods: ['GET' , 'POST']
    defaults: { _controller: AppBundle:Web:create }


update_article:
    path: /articles/update/{id}
    methods: ['GET' , 'POST']
    defaults: { _controller: AppBundle:Web:update }
    requirements:
        id: '\d+'

delete_article:
    path: /articles/{id}
    methods: GET
    defaults: { _controller: AppBundle:Web:delete }
    requirements:
        id: '\d+'

send_file:
    path: /sendfile
    methods: GET
    defaults: { _controller: AppBundle:Web:file }

info_after_auth:
    path: /info
    methods: GET
    defaults: { _controller: AppBundle:Web:info }